### ISSUE TITLE
Investigate using `Ember.computed.equal` for `talkByCurrentUser` on topic-card component.

### ISSUE THREAD

**Issue by AO16** [embernati/lightning#23]
For some reason, I wasn't able to get this to work. Was wondering if it had something to do with `meetupDates` being a service?

**Comment by jimmay5469** [comment]
`Ember.computed.equal` is supposed to compare a dynamic value with a hardcoded value, not two dynamic values.  This had me pretty confused for a minute until I went back and looked at the documentation a second time.

See:
http://emberjs.com/api/classes/Ember.computed.html#method_equal

**Comment by AO16** [comment]
Ha, that would make sense then. Thanks!
