### ISSUE TITLE
Development defaults for database connection

### ISSUE THREAD

**Issue by RobinDaugherty** [embernati/lightning#26]
Set up default development configuration so that in development, it gathers database connection information (perhaps by prompting the user?) instead of having it connect to the production database.

**Comment by jimmay5469** [comment]
The importance of this became very evident to me last night!

**Comment by AO16** [comment]
https://github.com/embernati/lightning/pull/29

**Comment by AO16** [comment]
I think this PR will be nice for now so that we're not hitting production, but having the user define will be a nice update to that.

**Comment by AO16** [comment]
After seeing how simple it was to add a dev firebase endpoint, I am feeling like if someone working on this project REALLY wants to create their own env then they can just update environment.js on their fork and deal with the merge conflicts. I don't anticipate too many changes in that file though, so they probably wouldn't have to do much at all to maintain their own environment. Maybe we could just have a quick note about it in the README. Thoughts?

**Comment by jimmay5469** [comment]
I don't think I would even worry about adding it to the README, I think what you have in #29 is enough, we can always re-open this later or create another issue if we decide we need something more thorough.
