### ISSUE TITLE
Allow for scheduling talk date

### ISSUE THREAD

**Issue by jimmay5469** [embernati/lightning#5]
If we allow a person to schedule a date where they can present the topic, then do we need the volunteer toggle button anymore?

**Comment by jimmay5469** [comment]
We could replace the volunteer toggle button with a button to present at the next meetup, and also a second button to present today if today is a meetup.

Once someone has clicked the button the buttons could be replaced with their avatar and username.

The user that has signed up would have the ability to unschedule themselves.

**Comment by AO16** [comment]
:+1:

**Comment by AO16** [comment]
I was going to take a look at this one, if that's cool.

**Comment by jimmay5469** [comment]
That would be awesome, this feature will make things a lot nicer!

**Comment by AO16** [comment]
https://github.com/embernati/lightning/pull/17
